import {useEffect,useRef,useState} from 'react';
import {ArrowRight,ChevronLeft,ChevronRight,Download,FileText,Layers,Mic,Settings2,Sparkles,Check,Loader2,X,Save,RefreshCw} from 'lucide-react';
import {api,Page,Project,Settings,GenerationJob} from './types';
import GenerationProgress from './GenerationProgress';
import './modal.css';
import {toPng} from 'html-to-image';

const roles:Record<string,string>={cover:'封面',hook:'引入',concept:'概念',explain:'原理',example:'案例',myth:'误区',summary:'总结',cta:'互动'};
export default function App(){
 const [article,setArticle]=useState(''),[aspectRatio,setAspectRatio]=useState<'9:16'|'16:9'>('9:16');
 const [project,setProject]=useState<Project|null>(null),[index,setIndex]=useState(0),[draft,setDraft]=useState<Page|null>(null),[dirty,setDirty]=useState(false);
 const [settings,setSettings]=useState<Settings>({base_url:'https://api.openai.com/v1',model:'',key_configured:false}),[modal,setModal]=useState(false);
 const [busy,setBusy]=useState(false),[status,setStatus]=useState(''),[error,setError]=useState(''),[tab,setTab]=useState('content'),[instruction,setInstruction]=useState('');
 const [apiKey,setApiKey]=useState(''),[testing,setTesting]=useState(false),[connectionStatus,setConnectionStatus]=useState<{ok:boolean;message:string}|null>(null);
 const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const [generation,setGeneration]=useState<GenerationJob|null>(null),[connectionError,setConnectionError]=useState('');
 const pollSession=useRef(0);
 async function refresh(){setSettings(await api('/settings/model'));}
 useEffect(()=>{refresh().catch(e=>setError(e.message));const saved=localStorage.getItem('cadence-job');if(saved){setBusy(true);setGeneration({id:saved,status:'running',message:'正在恢复任务进度'});poll(saved)}else{const current=new URLSearchParams(window.location.search).get('project')||localStorage.getItem('cadence-project');if(current)api<Project>('/projects/'+encodeURIComponent(current)).then(p=>accept(p)).catch(e=>setError(e.message))}return()=>{pollSession.current++;if(timer.current)clearTimeout(timer.current)}},[]);
 useEffect(()=>{const fn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn)},[dirty]);
 function accept(p:Project,i=0){localStorage.setItem('cadence-project',p.id);setProject(p);setTab('content');setIndex(i);setDraft(structuredClone(p.content.pages[i]));setDirty(false)}
 function mayLeave(){return !dirty||window.confirm('当前页有未保存的修改，确定放弃吗？')}
 async function action(fn:()=>Promise<void>){setError('');setBusy(true);try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function poll(id:string,session=pollSession.current){try{const response=await fetch('/api/generations/'+encodeURIComponent(id),{signal:AbortSignal.timeout(15000)});if(session!==pollSession.current)return;if(response.status===404){localStorage.removeItem('cadence-job');setGeneration(null);setError('任务不存在，请重新生成。');setBusy(false);return}if(!response.ok)throw new Error('暂时无法读取任务进度。');const job:GenerationJob=await response.json();if(session!==pollSession.current)return;setGeneration(job);setStatus(job.message);setConnectionError('');if(job.status==='completed'){const result=await api<Project>('/projects/'+job.project_id);if(session!==pollSession.current)return;accept(result);localStorage.removeItem('cadence-job');setBusy(false)}else if(job.status==='failed'){localStorage.removeItem('cadence-job');setError(job.message);setBusy(false)}else timer.current=setTimeout(()=>poll(id,session),1000)}catch{if(session!==pollSession.current)return;setConnectionError('连接暂时中断。');timer.current=setTimeout(()=>poll(id,session),4000)}}
 async function generate(){if(!mayLeave())return;setError('');setConnectionError('');setGeneration(null);setBusy(true);setStatus('正在提交文章');pollSession.current++;if(timer.current)clearTimeout(timer.current);try{const job=await api<GenerationJob>('/generations','POST',{article,aspect_ratio:aspectRatio});setGeneration(job);localStorage.setItem('cadence-job',job.id);poll(job.id)}catch(e){setError((e as Error).message);setBusy(false)}}
 function change<K extends keyof Page>(key:K,value:Page[K]){if(draft){setDraft({...draft,[key]:value});setDirty(true)}}
 async function save(){if(!project||!draft)return;accept(await api(`/projects/${project.id}/pages/${draft.id}`,'PATCH',{page:draft,revision:project.revision}),index);setStatus('当前页已保存')}
 function select(i:number){if(project&&mayLeave()){setIndex(i);setDraft(structuredClone(project.content.pages[i]));setDirty(false)}}
 async function download(kind:string){if(!project)return;if(dirty)await save();const r=await fetch(`/api/projects/${project.id}/export/${kind}`);if(!r.ok)throw new Error('导出失败');const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=kind==='html'?'cadence.html':kind==='script'?'narration.md':'project.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 const slideRef=useRef<HTMLElement|null>(null);
 const activeRatio=project?.aspect_ratio|| (project?'16:9':aspectRatio);
 const video=activeRatio==='16:9';
 async function downloadImage(){if(!slideRef.current)return;if(dirty)await save();await document.fonts.ready;const node=slideRef.current;if(node.scrollHeight>node.clientHeight+2)throw new Error('当前页文字超出画布，请精简正文或重点后再下载。');const a=document.createElement('a');a.download=`Cadence-${index+1}.png`;a.href=await toPng(node,{pixelRatio:1,canvasWidth:video?1920:1080,canvasHeight:video?1080:1920});a.click();setStatus('当前页图片已下载')}
 const page=draft;const count=project?.content.pages.length||0;
 return <div className="app-shell">
  <div className="workspace"><header className="topbar"><div className="wordmark">Cadence<span>创作工作台</span></div><div className="top-actions"><span className="local-dot"/> 本地空间 <button onClick={()=>setModal(true)}><Settings2 size={15}/>模型设置</button></div></header>
   <section className="intro"><div><h1>让知识，变得好看又好懂<span>。</span></h1><p>一篇文章，一组讲解页。把你的下一次创作，从这里开始。</p></div></section>
   <div className="workflow"><span className={!busy&&!project?'step-current':''}><b>01</b>导入素材</span><i/><span className={generation&&(generation.status==='queued'||generation.status==='running')?'step-current':''}><b>02</b>智能编排</span><i/><span className={project&&!busy?'step-current':''}><b>03</b>打磨与导出</span></div>
   {generation&&<GenerationProgress job={generation} connectionError={connectionError}/>}
   {error&&<div role="alert" className="error-banner">{error}<button aria-label="关闭错误" onClick={()=>setError('')}><X size={16}/></button></div>}
   <main className="studio-grid">
    <section className="panel source-panel"><div className="panel-heading"><span><FileText size={17}/>文章素材</span><small>导入文字</small></div><div className="panel-content"><div className="field-header"><label htmlFor="article">原始文章</label></div><textarea id="article" className="article-input" placeholder={'粘贴一篇你想讲清楚的科普文章…\n\n我们会提炼重点、梳理叙事，自动规划合适的讲解页数。'} value={article} onChange={e=>setArticle(e.target.value)} maxLength={20000} disabled={busy}/><div className="input-foot"><span>纯文本 · 100–20,000 字</span><span>{article.length.toLocaleString()} 字</span></div><div className="section-label">生成格式</div><div className="format-options" role="group" aria-label="生成格式">{(['9:16','16:9'] as const).map(r=><button key={r} aria-pressed={aspectRatio===r} className={aspectRatio===r?'chosen':''} disabled={busy} onClick={()=>setAspectRatio(r)}><b>{r}</b><span>{r==='9:16'?'小红书图文':'视频讲解'}</span><small>{r==='9:16'?'竖版图片 · 无口播稿':'横版画面 · 附口播稿'}</small></button>)}</div><button className="primary generate" disabled={busy||article.trim().length<100} onClick={generate}>{busy?<Loader2 size={17} className="spin"/>:<Sparkles size={17}/>} {busy?'正在处理…':(aspectRatio==='9:16'?'生成图文':'生成视频讲解页')}{!busy&&<ArrowRight size={17}/>}</button><p className="source-note">请使用你有权处理的素材。原文不保存到项目；生成时会发送至配置的模型服务。</p></div></section>
    <section className="preview-panel"><div className="panel-heading"><span><Layers size={17}/>画布预览</span><small>{activeRatio} · {video?'视频画面':'图文'}</small></div><div className={'canvas '+(video?'landscape':'portrait')}>{page?<article ref={slideRef} className={'slide '+(video?'landscape':'portrait')}><div className="eyebrow"><span>知识笔记</span><span>{String(index+1).padStart(2,'0')} / {count}</span></div><h1>{page.title}</h1><p className="body">{page.body}</p><div className="concepts">{page.highlights.map((h,i)=><div className="concept" key={i}><b>{String(i+1).padStart(2,'0')}</b><span>{h}</span></div>)}</div><footer><span>保持好奇 · 把知识讲明白</span><span>{roles[page.role]}</span></footer></article>:<div className="empty-canvas"><div className="empty-art"><div/><Layers size={40}/></div><h2>每个好问题，都值得一页好解释。</h2><p>在左侧粘贴文章，选择生成格式。<br/>你的第一组讲解页，会出现在这里。</p></div>}</div><div className="page-navigation"><button aria-label="上一页" disabled={!project||index===0||busy} onClick={()=>select(index-1)}><ChevronLeft size={18}/></button><div>{project?project.content.pages.map((p,i)=><button key={p.id} aria-label={'第'+(i+1)+'页'} className={index===i?'selected':''} disabled={busy} onClick={()=>select(i)}>{i+1}</button>):<span>等待创作 · 自动规划页数</span>}</div><button aria-label="下一页" disabled={!project||index===count-1||busy} onClick={()=>select(index+1)}><ChevronRight size={18}/></button></div></section>
    <section className="panel editor-panel"><div className="panel-heading"><span><Settings2 size={17}/>内容打磨</span><small>{dirty?'有未保存修改':'逐页编辑'}</small></div><div className="editor-tabs"><button className={tab==='content'||!video?'active':''} onClick={()=>setTab('content')}><FileText size={15}/>页面内容</button>{video&&<button className={tab==='voice'?'active':''} onClick={()=>setTab('voice')}><Mic size={15}/>口播稿</button>}</div>{page?<div className="panel-content"><div className="editing-label">第 {index+1} 页 <span>{roles[page.role]}</span></div><fieldset disabled={busy}>{tab==='content'||!video?<><label>页面标题<input maxLength={60} value={page.title} onChange={e=>change('title',e.target.value)}/></label><label>页面类型<select value={page.role} onChange={e=>change('role',e.target.value)}>{Object.entries(roles).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>核心讲解<textarea rows={7} maxLength={400} value={page.body} onChange={e=>change('body',e.target.value)}/></label><label>重点标注 <small>每行一条，最多 3 条</small><textarea rows={3} value={page.highlights.join('\n')} onChange={e=>change('highlights',e.target.value.split('\n').slice(0,3))}/></label><label>视觉建议<textarea rows={2} maxLength={300} value={page.visual_direction} onChange={e=>change('visual_direction',e.target.value)}/></label></>:<><div className="voice-stat"><Mic size={22}/><div>预计 {Math.round(page.narration.length/(project?.pace||180)*60)} 秒<small>按 {project?.pace||180} 字 / 分钟估算，非实际配音</small></div></div><label>逐页口播稿<textarea rows={15} maxLength={600} value={page.narration} onChange={e=>change('narration',e.target.value)}/></label><small>{page.narration.length} 字 · 建议 30–60 秒</small></>}{page.review_flags.length>0&&<div className="review-flags">待核实{page.review_flags.map((f,i)=><p key={i}>{f}</p>)}</div>}<button className="primary save" disabled={!dirty} onClick={()=>action(save)}><Save size={15}/>保存当前页</button><div className="regenerate"><label>想让这一页更好？<input value={instruction} maxLength={1000} onChange={e=>setInstruction(e.target.value)} placeholder="例如：用生活中的比喻解释"/></label><button className="secondary" disabled={!instruction.trim()||dirty} onClick={()=>action(async()=>{if(!project)return;setStatus('正在重写当前页');accept(await api(`/projects/${project.id}/pages/${page.id}/regenerate`,'POST',{instruction,revision:project.revision}),index);setStatus('当前页已重新生成')})}><RefreshCw size={14}/>重新生成此页</button>{dirty&&<small>先保存修改，再重新生成</small>}</div></fieldset></div>:<div className="editor-empty"><FileText size={28}/><h3>让每一页，更清楚。</h3><p>生成后，在这里编辑标题和重点。<br/>{video?'视频模式同时提供逐页口播稿。':'图文模式专注页面内容。'}</p></div>}</section>
   </main><footer className="workspace-footer"><span role="status">{busy?<Loader2 className="spin" size={14}/>:<span className="local-dot"/>}{status||'准备就绪 · 让下一个好故事发生'}</span><div><button disabled={!project||busy} onClick={()=>action(()=>download('json'))}>备份项目</button>{video&&<button disabled={!project||busy} onClick={()=>action(()=>download('script'))}><Mic size={15}/>导出口播稿</button>}<button disabled={!project||busy} onClick={()=>action(downloadImage)}><Download size={15}/>下载当前页图片</button><button className="primary" disabled={!project||busy} onClick={()=>action(()=>download('html'))}><Download size={15}/>导出网页</button></div></footer>
</div>{modal&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="模型设置"><div className="panel-heading"><span>模型设置</span><button aria-label="关闭设置" onClick={()=>{setApiKey('');setConnectionStatus(null);setModal(false)}}><X size={19}/></button></div><p>接入 OpenAI 或支持 JSON Schema 的兼容服务。</p><label>服务地址<input value={settings.base_url} onChange={e=>{setSettings({...settings,base_url:e.target.value});setConnectionStatus(null)}}/></label><label>模型名称<input value={settings.model} placeholder="填写账户可用的模型 ID" onChange={e=>{setSettings({...settings,model:e.target.value});setConnectionStatus(null)}}/></label><label>接口密钥<input type="password" autoComplete="new-password" spellCheck={false} value={apiKey} placeholder={settings.key_configured?'已配置，留空保留原密钥':'粘贴你的 API Key'} onChange={e=>{setApiKey(e.target.value);setConnectionStatus(null)}} maxLength={1024}/></label><div className="key-status">API Key：{settings.key_configured?'已配置':'尚未配置'}<p>密钥保存在本机 backend/.env，不会回传到页面。留空保留原密钥，输入新值则替换。</p></div>{connectionStatus&&<p role="status" className={connectionStatus.ok?'connection-success':'modal-error'}>{connectionStatus.message}</p>}{error&&<p role="alert" className="modal-error">{error}</p>}<div className="modal-actions"><button disabled={busy||testing} className="secondary" onClick={async()=>{setError('');setConnectionStatus(null);setTesting(true);try{setConnectionStatus(await api('/settings/model/test','POST',{base_url:settings.base_url,model:settings.model,api_key:apiKey}))}catch(e){setConnectionStatus({ok:false,message:(e as Error).message})}finally{setTesting(false)}}}>{testing?<Loader2 size={16} className="spin"/>:<RefreshCw size={16}/>} {testing?'正在测试…':'测试连接'}</button><button disabled={busy||testing} className="primary" onClick={()=>action(async()=>{setSettings(await api('/settings/model','PUT',{base_url:settings.base_url,model:settings.model,api_key:apiKey}));setApiKey('');setConnectionStatus(null);setModal(false);setStatus('模型设置已保存')})}><Check size={16}/>保存设置</button></div></section></div>}
 </div>
}
