import {useEffect,useRef,useState} from 'react';
import {ArrowRight,ChevronLeft,ChevronRight,Download,FileText,Layers,Mic,Settings2,Sparkles,Check,Loader2,X,BookOpen,Save,RefreshCw} from 'lucide-react';
import {api,Page,Project,Settings} from './types';

const roles:Record<string,string>={cover:'封面',hook:'引入',concept:'概念',explain:'原理',example:'案例',myth:'误区',summary:'总结',cta:'互动'};
const sample='天空为什么是蓝色的？\n\n阳光看起来接近白色，实际上包含不同颜色的光。不同颜色的光具有不同的波长。当阳光穿过大气，空气分子会将光散射到不同方向。较短波长的光比长波长的光更容易被散射，所以我们从天空各个方向接收到的散射光往往偏蓝。\n\n日落时，阳光穿过大气的路径更长，较短波长的光在途中被散射，直达眼睛的光就可能偏红或偏橙。不过，云和气溶胶也会影响实际观察到的颜色。';
export default function App(){
 const [article,setArticle]=useState(''),[audience,setAudience]=useState('普通成年人'),[tone,setTone]=useState('亲切、清晰、有好奇心'),[pace,setPace]=useState(180);
 const [project,setProject]=useState<Project|null>(null),[index,setIndex]=useState(0),[draft,setDraft]=useState<Page|null>(null),[dirty,setDirty]=useState(false);
 const [settings,setSettings]=useState<Settings>({base_url:'https://api.openai.com/v1',model:'',key_configured:false}),[modal,setModal]=useState(false),[history,setHistory]=useState<{id:string;title:string}[]>([]);
 const [busy,setBusy]=useState(false),[status,setStatus]=useState(''),[error,setError]=useState(''),[tab,setTab]=useState('content'),[instruction,setInstruction]=useState('');
 const [apiKey,setApiKey]=useState('');
 const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 async function refresh(){setHistory(await api('/projects'));setSettings(await api('/settings/model'));}
 useEffect(()=>{refresh().catch(e=>setError(e.message));const saved=localStorage.getItem('cadence-job');if(saved){setBusy(true);poll(saved)}return()=>{if(timer.current)clearTimeout(timer.current)}},[]);
 useEffect(()=>{const fn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn)},[dirty]);
 function accept(p:Project,i=0){setProject(p);setIndex(i);setDraft(structuredClone(p.content.pages[i]));setDirty(false)}
 function mayLeave(){return !dirty||window.confirm('当前页有未保存的修改，确定放弃吗？')}
 async function action(fn:()=>Promise<void>){setError('');setBusy(true);try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function poll(id:string){try{const job=await api<{status:string;message:string;project_id?:string}>('/generations/'+id);setStatus(job.message);if(job.status==='completed'){accept(await api('/projects/'+job.project_id));localStorage.removeItem('cadence-job');setBusy(false);await refresh()}else if(job.status==='failed'){localStorage.removeItem('cadence-job');setError(job.message);setBusy(false)}else timer.current=setTimeout(()=>poll(id),1800)}catch(e){setError((e as Error).message+' 刷新页面可重新连接任务。');setBusy(false)}}
 async function generate(){if(!mayLeave())return;setError('');setBusy(true);setStatus('正在提交文章');try{const job=await api<{id:string}>('/generations','POST',{article,audience,tone,pace});localStorage.setItem('cadence-job',job.id);poll(job.id)}catch(e){setError((e as Error).message);setBusy(false)}}
 function change<K extends keyof Page>(key:K,value:Page[K]){if(draft){setDraft({...draft,[key]:value});setDirty(true)}}
 async function save(){if(!project||!draft)return;accept(await api(`/projects/${project.id}/pages/${draft.id}`,'PATCH',{page:draft,revision:project.revision}),index);setStatus('当前页已保存')}
 function select(i:number){if(project&&mayLeave()){setIndex(i);setDraft(structuredClone(project.content.pages[i]));setDirty(false)}}
 async function download(kind:string){if(!project)return;if(dirty)await save();const r=await fetch(`/api/projects/${project.id}/export/${kind}`);if(!r.ok)throw new Error('导出失败');const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=kind==='html'?'cadence.html':kind==='script'?'narration.md':'project.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 const page=draft;const count=project?.content.pages.length||0;
 return <div className="app-shell">
  <aside className="rail"><a className="brand-mark" href="/" aria-label="Cadence 首页">c<span>•</span></a><div className="rail-divider"/><button className="rail-active" aria-label="创作工作台"><Layers size={21}/></button><button title="模型设置" aria-label="模型设置" onClick={()=>setModal(true)}><Settings2 size={21}/></button><span className="rail-bottom">LOCAL<br/>STUDIO</span></aside>
  <div className="workspace"><header className="topbar"><div className="wordmark">cadence<span>创作工作台</span></div><div className="top-actions"><span className="local-dot"/> 本地空间 <button onClick={()=>setModal(true)}><Settings2 size={15}/>模型设置</button></div></header>
   <section className="intro"><div><div className="kicker">IDEAS INTO STORIES</div><h1>让知识，变得好看又好懂<span>。</span></h1><p>一篇文章，一组讲解页。把你的下一次创作，从这里开始。</p></div><button className="secondary" disabled={busy} onClick={()=>{if(mayLeave())action(async()=>{accept(await api('/projects/demo','POST'));setStatus('已打开固定示例，未调用模型');await refresh()})}}><BookOpen size={16}/>体验示例<ArrowRight size={15}/></button></section>
   <div className="workflow"><span className="step-current"><b>01</b>导入素材</span><i/><span><b>02</b>智能编排</span><i/><span><b>03</b>打磨与导出</span><small>ARTICLE → VISUAL STORY</small></div>
   {error&&<div role="alert" className="error-banner">{error}<button aria-label="关闭错误" onClick={()=>setError('')}><X size={16}/></button></div>}
   <main className="studio-grid">
    <section className="panel source-panel"><div className="panel-heading"><span><FileText size={17}/>文章素材</span><small>01 / SOURCE</small></div><div className="panel-content"><div className="field-header"><label htmlFor="article">原始文章</label><button disabled={busy} onClick={()=>setArticle(sample)}>填入示例 ↗</button></div><textarea id="article" className="article-input" placeholder={'粘贴一篇你想讲清楚的科普文章…\n\n我们会提炼重点、梳理叙事，自动规划合适的讲解页数。'} value={article} onChange={e=>setArticle(e.target.value)} maxLength={20000} disabled={busy}/><div className="input-foot"><span>纯文本 · 100–20,000 字</span><span>{article.length.toLocaleString()} 字</span></div><div className="section-label">创作偏好</div><label>目标受众<select disabled={busy} value={audience} onChange={e=>setAudience(e.target.value)}><option>普通成年人</option><option>中学生</option><option>好奇的非专业读者</option></select></label><label>表达语气<select disabled={busy} value={tone} onChange={e=>setTone(e.target.value)}><option>亲切、清晰、有好奇心</option><option>严谨、克制、深入浅出</option><option>轻松、有趣、善用比喻</option></select></label><label>口播语速<select value={pace} disabled={busy} onChange={e=>setPace(Number(e.target.value))}><option value={150}>舒缓 · 150 字 / 分钟</option><option value={180}>自然 · 180 字 / 分钟</option><option value={220}>轻快 · 220 字 / 分钟</option></select></label><div className="style-choice"><span className="swatches"><i/><i/><i/></span><div>自然科普<small>奶油白 · 森林绿 · 统一排版</small></div><Check size={16}/></div><button className="primary generate" disabled={busy||article.trim().length<100} onClick={generate}>{busy?<Loader2 size={17} className="spin"/>:<Sparkles size={17}/>} {busy?'正在处理…':'生成讲解页'}{!busy&&<ArrowRight size={17}/>}</button><p className="source-note">请使用你有权处理的素材。原文不保存到项目；生成时会发送至配置的模型服务。</p>{history.length>0&&<label>最近的项目<select value={project?.id||''} disabled={busy} onChange={e=>{const id=e.target.value;if(id&&mayLeave())action(async()=>accept(await api('/projects/'+id)))}}><option value="">打开本地项目…</option>{history.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label>}</div></section>
    <section className="preview-panel"><div className="panel-heading"><span><Layers size={17}/>画布预览 {project?.generation_meta.model==='demo'&&<em>示例</em>}</span><small>9:16 · HTML</small></div><div className="canvas">{page?<article className={'slide '+page.role}><div className="eyebrow"><span>CADENCE · SCIENCE NOTES</span><span>{String(index+1).padStart(2,'0')} / {count}</span></div><h1>{page.title}</h1><p className="body">{page.body}</p><div className="concepts">{page.highlights.map((h,i)=><div className="concept" key={i}><b>{String(i+1).padStart(2,'0')}</b><span>{h}</span></div>)}</div><div className="orbit" aria-hidden="true"/><footer><span>保持好奇 · 把知识讲明白</span><span>{roles[page.role]}</span></footer></article>:<div className="empty-canvas"><div className="empty-art"><div/><Layers size={40}/></div><div className="kicker">YOUR NEXT STORY STARTS HERE</div><h2>每个好问题，都值得一页好解释。</h2><p>在左侧放入文章，或打开示例。<br/>你的第一组讲解页，会出现在这里。</p></div>}</div><div className="page-navigation"><button aria-label="上一页" disabled={!project||index===0||busy} onClick={()=>select(index-1)}><ChevronLeft size={18}/></button><div>{project?project.content.pages.map((p,i)=><button key={p.id} aria-label={'第'+(i+1)+'页'} className={index===i?'selected':''} disabled={busy} onClick={()=>select(i)}>{i+1}</button>):<span>等待创作 · 自动规划页数</span>}</div><button aria-label="下一页" disabled={!project||index===count-1||busy} onClick={()=>select(index+1)}><ChevronRight size={18}/></button></div></section>
    <section className="panel editor-panel"><div className="panel-heading"><span><Settings2 size={17}/>内容打磨</span><small>{dirty?'有未保存修改':'逐页编辑'}</small></div><div className="editor-tabs"><button className={tab==='content'?'active':''} onClick={()=>setTab('content')}><FileText size={15}/>页面内容</button><button className={tab==='voice'?'active':''} onClick={()=>setTab('voice')}><Mic size={15}/>口播稿</button></div>{page?<div className="panel-content"><div className="editing-label">PAGE {String(index+1).padStart(2,'0')} <span>{roles[page.role]}</span></div><fieldset disabled={busy}>{tab==='content'?<><label>页面标题<input maxLength={60} value={page.title} onChange={e=>change('title',e.target.value)}/></label><label>页面类型<select value={page.role} onChange={e=>change('role',e.target.value)}>{Object.entries(roles).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>核心讲解<textarea rows={7} maxLength={400} value={page.body} onChange={e=>change('body',e.target.value)}/></label><label>重点标注 <small>每行一条，最多 3 条</small><textarea rows={3} value={page.highlights.join('\n')} onChange={e=>change('highlights',e.target.value.split('\n').slice(0,3))}/></label><label>视觉建议<textarea rows={2} maxLength={300} value={page.visual_direction} onChange={e=>change('visual_direction',e.target.value)}/></label></>:<><div className="voice-stat"><Mic size={22}/><div>预计 {Math.round(page.narration.length/(project?.pace||180)*60)} 秒<small>按 {project?.pace||180} 字 / 分钟估算，非实际配音</small></div></div><label>逐页口播稿<textarea rows={15} maxLength={600} value={page.narration} onChange={e=>change('narration',e.target.value)}/></label><small>{page.narration.length} 字 · 建议 30–60 秒</small></>}{page.review_flags.length>0&&<div className="review-flags">待核实{page.review_flags.map((f,i)=><p key={i}>{f}</p>)}</div>}<button className="primary save" disabled={!dirty} onClick={()=>action(save)}><Save size={15}/>保存当前页</button><div className="regenerate"><label>想让这一页更好？<input value={instruction} maxLength={1000} onChange={e=>setInstruction(e.target.value)} placeholder="例如：用生活中的比喻解释"/></label><button className="secondary" disabled={!instruction.trim()||dirty} onClick={()=>action(async()=>{if(!project)return;setStatus('正在重写当前页');accept(await api(`/projects/${project.id}/pages/${page.id}/regenerate`,'POST',{instruction,revision:project.revision}),index);setStatus('当前页已重新生成')})}><RefreshCw size={14}/>重新生成此页</button>{dirty&&<small>先保存修改，再重新生成</small>}</div></fieldset></div>:<div className="editor-empty"><Mic size={28}/><h3>内容和声音，一起打磨。</h3><p>生成后，在这里编辑标题、重点<br/>和每一页的口播稿。</p></div>}</section>
   </main><footer className="workspace-footer"><span role="status">{busy?<Loader2 className="spin" size={14}/>:<span className="local-dot"/>}{status||'准备就绪 · 让下一个好故事发生'}</span><div><button disabled={!project||busy} onClick={()=>action(()=>download('json'))}>项目 JSON</button><button disabled={!project||busy} onClick={()=>action(()=>download('script'))}><Mic size={15}/>导出口播稿</button><button className="primary" disabled={!project||busy} onClick={()=>action(()=>download('html'))}><Download size={15}/>导出 HTML</button></div></footer>
</div>{modal&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="模型设置"><div className="panel-heading"><span>模型设置</span><button aria-label="关闭设置" onClick={()=>{setApiKey('');setModal(false)}}><X size={19}/></button></div><p>接入 OpenAI 或支持 JSON Schema 的兼容服务。</p><label>Base URL<input value={settings.base_url} onChange={e=>setSettings({...settings,base_url:e.target.value})}/></label><label>模型名称<input value={settings.model} placeholder="填写账户可用的模型 ID" onChange={e=>setSettings({...settings,model:e.target.value})}/></label><label>API Key<input type="password" autoComplete="new-password" spellCheck={false} value={apiKey} placeholder={settings.key_configured?'已配置，留空保留原密钥':'粘贴你的 API Key'} onChange={e=>setApiKey(e.target.value)} maxLength={1024}/></label><div className="key-status">API Key：{settings.key_configured?'已配置':'尚未配置'}<p>密钥保存在本机 backend/.env，不会回传到页面。留空保留原密钥，输入新值则替换。</p></div>{error&&<p role="alert" className="modal-error">{error}</p>}<button disabled={busy} className="primary" onClick={()=>action(async()=>{setSettings(await api('/settings/model','PUT',{base_url:settings.base_url,model:settings.model,api_key:apiKey}));setApiKey('');setModal(false);setStatus('模型设置已保存')})}><Check size={16}/>保存设置</button></section></div>}
 </div>
}
